export const data = [
  {
    logo: "Stripe",
    logoUrl: "https://cdn.simpleicons.org/stripe",
    applications: "12 apps",
    rate: 45,
    profit: "$2,450",
  },
  {
    logo: "PayPal",
    logoUrl: "https://cdn.simpleicons.org/paypal",
    applications: "8 apps",
    rate: 38,
    profit: "$1,890",
  },
  {
    logo: "Android",
    logoUrl: "https://cdn.simpleicons.org/android",
    applications: "15 apps",
    rate: 52,
    profit: "$3,120",
  },
  {
    logo: "GitHub",
    logoUrl: "https://cdn.simpleicons.org/github",
    applications: "20 apps",
    rate: 61,
    profit: "$4,560",
  },
  {
    logo: "Zoom",
    logoUrl: "https://cdn.simpleicons.org/zoom",
    applications: "6 apps",
    rate: 29,
    profit: "$980",
  },
  {
    logo: "Notion",
    logoUrl: "https://cdn.simpleicons.org/notion",
    applications: "10 apps",
    rate: 40,
    profit: "$2,100",
  },
  {
    logo: "Figma",
    logoUrl: "https://cdn.simpleicons.org/figma",
    applications: "14 apps",
    rate: 48,
    profit: "$3,340",
  },
  {
    logo: "Bruno",
    logoUrl: "https://cdn.simpleicons.org/bruno",
    applications: "25 apps",
    rate: 73,
    profit: "$5,800",
  },
  {
    logo: "Google",
    logoUrl: "https://cdn.simpleicons.org/google",
    applications: "18 apps",
    rate: 55,
    profit: "$4,100",
  },
  {
    logo: "Claude",
    logoUrl: "https://cdn.simpleicons.org/claude",
    applications: "7 apps",
    rate: 32,
    profit: "$1,450",
  },
];
